### ISSUE TITLE
Ditch most of the Persistence.py file

### ISSUE THREAD

**Issue by lizliz** [MunchLab/teaspoon#5]
The code in `teaspoon.TDA.Persistence.py` is largely legacy code from before we had nice python wrappers for `ripser`. This part of the package can be largely dumped since there's so little chance we'd use some of the more outdated persistence computation packages. 

Even the code in there for doing Ripser is my own (sloooooooooooooow) code for reading in the text file outputs from the C++ ripser package. I doubt anything else in teaspoon is using those versions, but we'd also just have to make sure there were not lingering dependencies.

**Comment by barnesd8** [comment]
There are only a few helper functions with minimal external dependencies, and none of these are tda libraries, so I've removed anything unnecessary and left the helper functions that are used or that could be helpful.  Screenshot of functions left is below.
<img width="680" alt="Screenshot 2023-01-02 at 1 24 35 PM" src="https://user-images.githubusercontent.com/28761771/210267550-7c7c8832-4a31-4c5a-afee-af7c594c02c3.png">
