### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by lizliz** [MunchLab/teaspoon#7]
Got the following Email from Aras Asad, so putting it in here as an issue to be checked. Please note I'm not sure if he's looking at old or new version of teaspoon (we really need to get that fixed), so it's possible it's already a non-issue. 

---

Dear Liz,

I hope this email finds you and your respected family in a good health,

Using some of the TEASPOON software functionality, I have spotted a typo in one of the formulas in ' Carlsson Coordinates' vectorization method. The 1st four formulas are from adcock-carlsson and the fifth is from one of your papers. the fifth formula is written as:
f5(D) = ∑max{(yi − xi)}, which needs to be corrected to
f5(D) = max{(yi − xi)}.

I have checked and compared it with your paper (https://arxiv.org/pdf/1804.02261.pdf) too.

Thought I let you know to make the documentation more precise.

Best Wishes

Aras Asaad

**Comment by barnesd8** [comment]
Thanks I’ll get this checked out. I would expect by beginning of the semester to have it all cleaned up as well.

**Comment by barnesd8** [comment]
<img width="325" alt="Screenshot 2023-01-01 at 7 29 19 PM" src="https://user-images.githubusercontent.com/28761771/210188424-b21e0420-4037-44dd-8ed8-a45538c1fc3c.png">
